version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: api_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5052:5052'
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: api_database
      DB_USER: postgres
      DB_PASSWORD: example

volumes:
  db-data:
